version: "3.9"  # optional since v1.27.0
services:
  employee-service:
    image: docker-employee-service
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - employee-service
    ports:
      - "4000:4000"
